# Warmup

In [55]:
import pandas as pd

In [56]:
dict1 = { 'Name' : ['Priyang', 'Aadhya', 'Krisha', 'Vedant', 'Parshv',
                    'Mittal', 'Archana'],
                    'Marks': [98, 89, 99, 87, 90, 83, 99],
                    'Gender' : ['Male', 'Female', 'Female', 'Male', 'Male', 
                                'Female', 'Male']}
df1 = pd.DataFrame(dict1)
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99    Male

1. Display Top 3 Rows in set

In [57]:
df1.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female

Display last 3 rows in set

In [58]:
df1.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99    Male

3. Find shape of our dataset

In [59]:
df1.shape
# 7 rows and 3 columns

(7, 3)

In [60]:
print('Number of Rows', df1.shape[0])
print('Number of Columns', df1.shape[1])

Number of Rows 7
Number of Columns 3

4. Get Information about our dataset. Like total number of rows, total number of columns, datatypes of each column and memory requirements

In [61]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      object
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 296.0+ bytes

5. Check Null Values in dataset

In [62]:
df1.isnull().sum()  # Shows nulls by column

Name      0
Marks     0
Gender    0
dtype: int64

In [63]:
df1.isnull().sum(axis= 1)   # Shows the nulls by row

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

6. Overall Statistics of dataframe

In [64]:
df1.describe()

           Marks
count   7.000000
mean   92.142857
std     6.491753
min    83.000000
25%    88.000000
50%    90.000000
75%    98.500000
max    99.000000

In [65]:
df1.describe(include='all') # To include objects

           Name      Marks Gender
count         7   7.000000      7
unique        7        NaN      2
top     Priyang        NaN   Male
freq          1        NaN      4
mean        NaN  92.142857    NaN
std         NaN   6.491753    NaN
min         NaN  83.000000    NaN
25%         NaN  88.000000    NaN
50%         NaN  90.000000    NaN
75%         NaN  98.500000    NaN
max         NaN  99.000000    NaN

7. Find unique values from gender column

In [66]:
df1['Gender'].unique()

array(['Male', 'Female'], dtype=object)

8. Find the number of unique values from the gender column

In [67]:
df1['Gender'].nunique()

2

9. Display Count of Unique Values in Gender Column

In [68]:
df1['Gender'].value_counts()

Male      4
Female    3
Name: Gender, dtype: int64

10. Find the number of students having marks between 90 to 100 (inclusive) using the Between method

In [69]:
[(df1['Marks']>= 90) & (df1['Marks'] <= 100)]

[0     True
 1    False
 2     True
 3    False
 4     True
 5    False
 6     True
 Name: Marks, dtype: bool]

In [70]:
len(df1[(df1['Marks']>= 90) & (df1['Marks'] <= 100)])

4

In [71]:
df1['Marks'].between(90, 100)

0     True
1    False
2     True
3    False
4     True
5    False
6     True
Name: Marks, dtype: bool

In [72]:
sum(df1['Marks'].between(90, 100))

4

11. Find Average Marks

In [73]:
df1['Marks'].mean()

92.14285714285714

12. Apply Method

In [74]:
def marks(x):
    return x//2

In [75]:
df1['Marks'].apply(marks)

0    49
1    44
2    49
3    43
4    45
5    41
6    49
Name: Marks, dtype: int64

In [76]:
df1['Half_marks'] = df1['Marks'].apply(marks)
df1

      Name  Marks  Gender  Half_marks
0  Priyang     98    Male          49
1   Aadhya     89  Female          44
2   Krisha     99  Female          49
3   Vedant     87    Male          43
4   Parshv     90    Male          45
5   Mittal     83  Female          41
6  Archana     99    Male          49

More concise version using lambda function

In [77]:
df1['Marks'].apply(lambda x:x/2)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

Length of strings

In [78]:
df1['Name'].apply(len)

0    7
1    6
2    6
3    6
4    6
5    6
6    7
Name: Name, dtype: int64

13. Map Function

In [79]:
df1

      Name  Marks  Gender  Half_marks
0  Priyang     98    Male          49
1   Aadhya     89  Female          44
2   Krisha     99  Female          49
3   Vedant     87    Male          43
4   Parshv     90    Male          45
5   Mittal     83  Female          41
6  Archana     99    Male          49

In [80]:
df1['Male_Female'] = df1['Gender'].map({'Male': 1, 'Female': 0})
df1

      Name  Marks  Gender  Half_marks  Male_Female
0  Priyang     98    Male          49            1
1   Aadhya     89  Female          44            0
2   Krisha     99  Female          49            0
3   Vedant     87    Male          43            1
4   Parshv     90    Male          45            1
5   Mittal     83  Female          41            0
6  Archana     99    Male          49            1

14. Drop the column(s)

In [81]:
df1.drop('Male_Female', axis = 1)

      Name  Marks  Gender  Half_marks
0  Priyang     98    Male          49
1   Aadhya     89  Female          44
2   Krisha     99  Female          49
3   Vedant     87    Male          43
4   Parshv     90    Male          45
5   Mittal     83  Female          41
6  Archana     99    Male          49

Make a list to drop multiple

In [82]:
df1.drop(['Male_Female', 'Half_marks'], axis = 1)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99    Male

In [83]:
df1

      Name  Marks  Gender  Half_marks  Male_Female
0  Priyang     98    Male          49            1
1   Aadhya     89  Female          44            0
2   Krisha     99  Female          49            0
3   Vedant     87    Male          43            1
4   Parshv     90    Male          45            1
5   Mittal     83  Female          41            0
6  Archana     99    Male          49            1

To modify existing datafram use inplace=True

In [84]:
df1.drop(['Male_Female', 'Half_marks'], axis = 1, inplace=True)
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99    Male

15. Print Name of the Columns

In [86]:
df1.columns

Index(['Name', 'Marks', 'Gender'], dtype='object')

In [87]:
df1.index

RangeIndex(start=0, stop=7, step=1)

16. Sort th dataframe as per the marks column

Both methods work:

In [88]:
df1['Marks'].sort_values()

5    83
3    87
1    89
4    90
0    98
2    99
6    99
Name: Marks, dtype: int64

In [89]:
df1.sort_values(by= 'Marks')

      Name  Marks  Gender
5   Mittal     83  Female
3   Vedant     87    Male
1   Aadhya     89  Female
4   Parshv     90    Male
0  Priyang     98    Male
2   Krisha     99  Female
6  Archana     99    Male

In [90]:
df1.sort_values(by= 'Marks', ascending=False)

      Name  Marks  Gender
2   Krisha     99  Female
6  Archana     99    Male
0  Priyang     98    Male
4   Parshv     90    Male
1   Aadhya     89  Female
3   Vedant     87    Male
5   Mittal     83  Female

In [91]:
df1.sort_values(by= ['Marks', 'Gender'], ascending=False)

      Name  Marks  Gender
6  Archana     99    Male
2   Krisha     99  Female
0  Priyang     98    Male
4   Parshv     90    Male
1   Aadhya     89  Female
3   Vedant     87    Male
5   Mittal     83  Female

17. Display name and marks of the female students

In [92]:
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   Krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99    Male

In [99]:
df1[df1['Gender'] == 'Female'][['Name', 'Marks']]

     Name  Marks
1  Aadhya     89
2  Krisha     99
5  Mittal     83

Alternative way

In [102]:
df1[df1['Gender'].isin(['Female'])][['Name', 'Marks']]

     Name  Marks
1  Aadhya     89
2  Krisha     99
5  Mittal     83